### PR TITLE
WIP: feat(transport): single topic with sql filters on subscription

### PR DESCRIPTION
**Pull request by riezebosch**
This is an experiment I did on using a single topic and using sql filter rules on subscriptions for routing. By setting the destination address on the `To` field, one can use that information on the topic filter.

I'm curious what you think about it since it's more in line with the RabbitMq solution where routing keys are used on a single exchange.

Some background: https://learn.microsoft.com/en-us/azure/service-bus-messaging/topic-filters

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Hi @riezebosch , could you explain some more about this? What does it achieve? And how is it different from Rebus' current way of managing the topology?

**Comment by riezebosch** [comment]
Instead of having a topic per message type you now get a single topic which all messages are routed through. On that single topic, you get a subscription per endpoint with filters for each subscribed message.

Screenshot 2022-11-21 at 10 30 03
Screenshot 2022-11-21 at 10 30 33
Screenshot 2022-11-21 at 10 30 53

This could also simplify the transport a little since you no longer need a separate topic client per topic nor batching per destination address.

**Comment by mookid8000** [comment]
Ah ok, I see. But I am not sure that I think Rebus should be changed this way.

The current way of using Azure Service Bus entities is IMO closely aligned with how RabbitMQ's concepts work – i.e. when working with RabbitMQ exchanges of the type "topic", the "routing key" is interpreted as a topic, and it results in messages being routed to queues that are bound to that topic.

Similar to this, Rebus uses Azure Service Bus by treating "topics" as topics, and "subscriptions" similar to how bindings work with RabbitMQ.

Even though it _could_ bring some benefits having only a single topic, I think it would be quite unexpected that the topic entity in ASB would not actually represent a topic.

That's my opinion. Feel free to change my mind 😁

**Comment by riezebosch** [comment]
From a user perspective, I don't expect much confusion on the "topic" name since there is in the Rebus API no notion of such a thing anyway. It is only the Rebus internals where topics are constructed and created from type names and messages are sent or published to these topics. With the current implementation, a topic is synonymous with an event type. 

It is only Azure ServiceBus that gives another meaning to the word topic, compared to RabbitMQ where it is a specialization of an Exchange.

In my quest to make Rebus less dotnet-specific I already added another `TopicNameConvention` to use the configured custom type names instead of `SimpleAssemblyQualifiedName`. In fact, from [the documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.to?view=azure-dotnet) it is a valid scenario to use the `To` field value in "rule-driven [auto-forward chaining](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding) scenarios to indicate the intended logical destination of the message".

rabbitmq | azure servicebus
---------|-----
topic exchange | topic
binding       | subscription
routing key | sql rule filter
queue        | queue

Both implementations use the message type for routing, the first as the routing key and within a SQL rule filter for the other.

**Comment by mookid8000** [comment]
> From a user perspective, I don't expect much confusion on the "topic" name since there is in the Rebus API no notion of such a thing anyway. It is only the Rebus internals where topics are constructed and created from type names and messages are sent or published to these topics. With the current implementation, a topic is synonymous with an event type.

What do you call this?

```csharp
ITopicsApi topics = bus.Advanced.Topics;

await topics.Publish("my-topic", new SomeEvent());
```

😉 

But yeah, to some level I agree with you on this – at least, it's nowhere near as hardly manifested as Azure Service Bus does it, with explicit creation of durable entities to represent topics. With Rebus and RabbitMQ, topics don't have to exist(*) to be able to publish to them, but in the form of RabbitMQ's BINDINGS, they do often exist (if not literally, then at least in the form of a string containing wildcards).

> It is only Azure ServiceBus that gives another meaning to the word topic, compared to RabbitMQ where it is a specialization of an Exchange.

I don't think I agree with you that "... (topics are) a specialization of an Exchange" with RabbitMQ. Or at least that's not how I perceive it.

You are right that exchanges can have a type, one of them being "topics". I think you should think of a **topics exchange** as a type of exchange that interprets a message's **routing key** as a **topic**. So the exchange does not represent a topic or anything like that, the exchange represents a specific logic pertaining to the routing key, whereby it is interpreted as a topic, which has implications for how messages are distributed.

At least that's how Rebus uses RabbitMQ 🙂 because I am aware that you CAN also raise your level of RabbitMQness one bit and use the exchange as a topic!

> (...) In fact, from [the documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.to?view=azure-dotnet) it is a valid scenario to use the To field value in "rule-driven [auto-forward chaining](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding) scenarios to indicate the intended logical destination of the message". (...)

I can see that. But my opinion at this point is that using a single topic combined with filters on subscriptions would basically just be "another way to do it", which just happens to be a little bit harder to understand.

E.g. I think it's pretty nice that when you look at your Azure Service Bus instance in Azure Portal, or by using [Service Bus Explorer)(https://github.com/paolosalvatori/ServiceBusExplorer), then the "Topics" node expands to list all of the topics used on that particular instance.

Also I totally understand that these things are basically very subjective. While writing this I remembered how I encountered people using RabbitMQ exchanges as their topics, which in my view was kind of funny, because then what are topics on bindings for? But I can also see it the other way around: If my topics are on the bindings, then when would I ever have more than one topics exchange?

----
(*) Whatever that means

**Comment by riezebosch** [comment]
Certainly, it is nothing more than "another way to do it". On my current assignment, I also opted to "go with the framework" and embrace the topic per type. Others were scared by the number of topics that got created, but for me that was a sign the events were to granular. I also like to be explicit: these are the types you can expect. At the same time, we already need a place for documenting the shape of the messages since we chose not to do contract sharing (as in a shared library or nuget package containing the message types).

What I do like as the outcome of the experiment is the somewhat simpler topology, less "infrastructure" required, and a somewhat easier publishing mechanism. Another plus is that it is easier to find which messages are routed to which queue, since it is all just rules on a single subscription per endpoint.

**Comment by mookid8000** [comment]
Hi @riezebosch , I really appreciate the work you've done, and I love having assumptions and doctrines questioned and challenged, but in this case I really believe that topics are best represented as "topic"s and bindings as "subscription"s in Azure Service Bus.

Therefore I am closing this PR.

Thanks again though 🙂  keep hitting me 😅

**Comment by riezebosch** [comment]
No problem at all! As I said, I also enjoyed the experiment. I want to refactor the transport and split out its responsibilities, thereby creating an extension point that would make it possible to opt-in to this behavior by decorating specific parts. But that turned out not to be so easy as of now.

**Pull request closed without merging**
