### PR TITLE
feat(message): use ServiceBusMessage properties

### PR DESCRIPTION
**Pull request by riezebosch**
Remove rbs2-* headers that for data that is already available on the outgoing ServiceBusMessage Use SericeBusMessage properties from incoming message to recreate custom rbs2-* headers

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by riezebosch** [comment]
I understand this change implies that all consumers connected to the bus needed to upgrade. If you're open to this change, I might also introduce an opt-out flag to still use the new behavior on incoming messages but still publish the rbs2-* custom properties.

**Comment by riezebosch** [comment]
This improves interoperability with other producers by using the provided `Id` and `CorrelationId`.

**Comment by mookid8000** [comment]
Hi @riezebosch , I actually quite like this change, BUT I think it should be opt-in. 🙂 

Ideally, the transport initially worked like this, but it didn't, and that's why it does what it does today: Transfers all Rebus headers as custom properties, exposing some of them to tools (like [Service Bus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer)) for specific headers that have also make sense to Azure Service Bus.

Could you make it possible to e.g.

```csharp
services.AddRebus(
    configure => configure
        .Transport(t => t.UseAzureServiceBus(...)
            .UseOnlyNativeHeadersWhenPossible())
);
```

or something like that?

**Comment by riezebosch** [comment]
Is it enough to only opt-out from the removal of `rbs2-*` headers? The copy of message-id and correlation-id have been there for [quite some time already](https://github.com/rebus-org/Rebus.AzureServiceBus/blame/0af1499717a60ffd57d16382dc2cfecbfa92aea4/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L512-L520). So you can safely assume on incoming messages that the message-id and correlation-id of the service bus message equals the value of the `rbs2-*` headers.

**Comment by mookid8000** [comment]
> Is it enough to only opt-out from the removal of rbs2-* headers? The copy of message-id and correlation-id have been there for [quite some time already](https://github.com/rebus-org/Rebus.AzureServiceBus/blame/0af1499717a60ffd57d16382dc2cfecbfa92aea4/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L512-L520). So you can safely assume on incoming messages that the message-id and correlation-id of the service bus message equals the value of the rbs2-* headers.

I guess you are right about the headers already present in the message's native fields.  So yes I think so (but we'll need to test this with a couple of betaversions before committing to it)

**Comment by riezebosch** [comment]
I've updated it to provide a boolean flag to opt-in for the default header removal. But then refactored it into the concepts I saw in the main Rebus package. Message conversion is decoupled from transport and injected, and the headers are removed via decoration (using a configuration extension).

This also creates an extension point for others to do different message conversions.

I'd love to do the same for separating the transport from the topics and queues management.

**Comment by mookid8000** [comment]
Hi @riezebosch , it looks really good 🙂 

I know this is a small thing, but could you maybe rename `IMessageConvert` to `IMessageConverter`? (along with its implementation)

**Comment by mookid8000** [comment]
btw there's a test failing, but I can see it's a test that I made 😅 so I'll merge your PR now!

**Comment by mookid8000** [comment]
Thanks for contributing 👍

**Pull request merged**
